[package]
name = "cartunes"
version = "0.1.0"
description = "Simple tuning comparison app for iRacing."
authors = ["Jay Oster <jay@kodewerx.org>"]
homepage = "https://github.com/parasyte/cartunes"
repository = "https://github.com/parasyte/cartunes"
edition = "2018"
readme = "README.md"
license = "MIT"
resolver = "2"

[dependencies]
copypasta = "0.7"
egui = { version = "0.13", default-features = false, features = ["single_threaded"] }
egui_wgpu_backend = "0.9"
directories = "3.0"
log = "0.4"
num_enum = { version = "0.5", default-features = false }
pollster = "0.2"
raw-window-handle = "0.3"
thiserror = "1.0"
toml_edit = "0.2"
wgpu = "0.9"
winit = "0.25"
winit_input_helper = "0.10"

[dependencies.egui_winit_platform]
version = "0.9"
default-features = false
features = ["clipboard", "webbrowser"]

[dependencies.env_logger]
version = "0.8"
default-features = false
features = ["atty", "humantime", "termcolor"]

[features]
default = ["optimize"]
optimize = ["log/release_max_level_warn"]

[patch.crates-io.egui_wgpu_backend]
git = "https://github.com/parasyte/egui_wgpu_backend.git"
rev = "75781ebd9ecd6264af502543650a8485fc2667ab"
