[config]
# This is the path to your documents directory with car tuning exports from the garage.
tuning_path = ''

# You can disable open history by setting the size to 0.
history_size = 10
open_history = []

[window]
